export default function TermsPage() {
  return (
    <article className="py-10 space-y-8 text-zinc-300 text-sm leading-relaxed">
      <div>
        <h1 className="text-2xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-xs text-zinc-500">Last updated: March 24, 2026</p>
      </div>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">1. Acceptance of Terms</h2>
        <p>
          By accessing or using ClipForge ("the Service"), you agree to be bound by these Terms of Service.
          If you do not agree with any part of these terms, you may not use the Service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">2. Description of Service</h2>
        <p>
          ClipForge is an AI-powered video marketing engine that generates short-form video content
          from brand websites. The Service includes website scraping, AI content generation,
          video creation, and social media posting capabilities.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">3. User Accounts</h2>
        <p>
          You must create an account to use the Service. You are responsible for maintaining the
          security of your account credentials and for all activity that occurs under your account.
          You must provide accurate and complete information when creating your account.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">4. Acceptable Use</h2>
        <p>You agree not to use the Service to:</p>
        <ul className="list-disc list-inside space-y-1.5 text-zinc-400">
          <li>Generate content that infringes on third-party intellectual property rights</li>
          <li>Create misleading, deceptive, or fraudulent content</li>
          <li>Scrape websites you do not have authorization to access</li>
          <li>Violate any applicable laws or regulations</li>
          <li>Distribute malware, spam, or harmful content</li>
          <li>Attempt to reverse-engineer or compromise the Service</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">5. Content Ownership</h2>
        <p>
          You retain ownership of the brand information you provide and the videos generated
          through the Service. However, you are solely responsible for ensuring that your use
          of generated content complies with applicable laws, platform terms of service,
          and third-party rights.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">6. Third-Party Services</h2>
        <p>
          The Service integrates with third-party platforms including TikTok, Instagram, and YouTube.
          Your use of these platforms is subject to their respective terms of service.
          We are not responsible for the availability, policies, or actions of third-party services.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">7. AI-Generated Content</h2>
        <p>
          Content generated by the Service uses artificial intelligence and may not always be accurate,
          appropriate, or suitable for your intended purpose. You are responsible for reviewing all
          generated content before publishing or distributing it.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">8. API Keys and Credentials</h2>
        <p>
          The Service may require you to provide API keys for third-party services (e.g., Google Gemini).
          You are responsible for the security and proper use of these keys.
          We do not store or transmit your API keys beyond what is necessary to provide the Service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">9. Limitation of Liability</h2>
        <p>
          The Service is provided "as is" without warranties of any kind. We shall not be liable
          for any indirect, incidental, special, consequential, or punitive damages arising from
          your use of the Service, including but not limited to loss of data, revenue, or profits.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">10. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your access to the Service at any time,
          with or without cause, and with or without notice. Upon termination, your right to use
          the Service will immediately cease.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">11. Changes to Terms</h2>
        <p>
          We may update these Terms from time to time. We will notify users of material changes
          by updating the "Last updated" date. Continued use of the Service after changes
          constitutes acceptance of the revised terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">12. Contact</h2>
        <p>
          If you have questions about these Terms, please contact us through the Service's
          support channels.
        </p>
      </section>
    </article>
  )
}
