export default function PrivacyPage() {
  return (
    <article className="py-10 space-y-8 text-zinc-300 text-sm leading-relaxed">
      <div>
        <h1 className="text-2xl font-bold text-white mb-2">Privacy Policy</h1>
        <p className="text-xs text-zinc-500">Last updated: March 24, 2026</p>
      </div>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">1. Introduction</h2>
        <p>
          This Privacy Policy describes how ClipForge ("we", "our", "the Service") collects, uses,
          and protects your information. By using the Service, you consent to the practices
          described in this policy.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">2. Information We Collect</h2>

        <h3 className="text-sm font-medium text-zinc-200">Account Information</h3>
        <p>
          When you create an account, we collect your email address and authentication credentials.
          If you sign in with Google, we receive your name and email from Google's OAuth service.
        </p>

        <h3 className="text-sm font-medium text-zinc-200">Brand Data</h3>
        <p>
          When you use the onboarding feature, we scrape publicly available content from the
          website URL you provide. This data is used to generate your brand brief and video content.
        </p>

        <h3 className="text-sm font-medium text-zinc-200">Generated Content</h3>
        <p>
          We store the videos, thumbnails, captions, and metadata generated by the Service,
          along with your curation decisions (save/skip actions).
        </p>

        <h3 className="text-sm font-medium text-zinc-200">Platform Connections</h3>
        <p>
          When you connect social media accounts (TikTok, Instagram, YouTube), we store
          OAuth access tokens and refresh tokens necessary to post content on your behalf.
          We also store your platform username and account ID.
        </p>

        <h3 className="text-sm font-medium text-zinc-200">Usage Data</h3>
        <p>
          We collect information about how you interact with the Service, including
          videos generated, save/skip actions, scheduling activity, and posting history.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">3. How We Use Your Information</h2>
        <ul className="list-disc list-inside space-y-1.5 text-zinc-400">
          <li>To provide and operate the Service</li>
          <li>To generate AI-powered brand briefs and video content</li>
          <li>To post and schedule content to your connected social media accounts</li>
          <li>To display analytics about your content performance</li>
          <li>To improve the Service and develop new features</li>
          <li>To communicate with you about your account or the Service</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">4. Data Storage and Security</h2>
        <p>
          Your data is stored in Supabase (PostgreSQL) with Row Level Security (RLS) enabled,
          ensuring that each user can only access their own data. OAuth tokens for connected
          platforms are stored encrypted in the database.
        </p>
        <p>
          We implement reasonable security measures to protect your information. However,
          no method of electronic storage is 100% secure, and we cannot guarantee absolute security.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">5. Third-Party Services</h2>
        <p>We use the following third-party services:</p>
        <ul className="list-disc list-inside space-y-1.5 text-zinc-400">
          <li><span className="text-zinc-300">Supabase</span> — Authentication and database hosting</li>
          <li><span className="text-zinc-300">Google Gemini API</span> — AI text generation for brand briefs and captions</li>
          <li><span className="text-zinc-300">Google Imagen API</span> — AI image generation for video backgrounds</li>
          <li><span className="text-zinc-300">TikTok API</span> — Video posting (when connected)</li>
          <li><span className="text-zinc-300">Instagram Graph API</span> — Reels posting (when connected)</li>
          <li><span className="text-zinc-300">YouTube Data API</span> — Shorts uploading (when connected)</li>
        </ul>
        <p>
          Each third-party service has its own privacy policy. We encourage you to review them.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">6. Data Sharing</h2>
        <p>
          We do not sell your personal information. We share data only in the following cases:
        </p>
        <ul className="list-disc list-inside space-y-1.5 text-zinc-400">
          <li>With third-party platforms when you explicitly choose to post content</li>
          <li>With AI service providers to generate content (website text sent to Gemini)</li>
          <li>When required by law or legal process</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">7. Your Rights</h2>
        <p>You have the right to:</p>
        <ul className="list-disc list-inside space-y-1.5 text-zinc-400">
          <li>Access the personal data we hold about you</li>
          <li>Request correction of inaccurate data</li>
          <li>Request deletion of your account and associated data</li>
          <li>Disconnect third-party platform connections at any time</li>
          <li>Export your data</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">8. Data Retention</h2>
        <p>
          We retain your data for as long as your account is active. When you delete your account,
          we will delete your personal data, generated content, and platform connections
          within 30 days. Some data may be retained in backups for a limited period.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">9. Cookies</h2>
        <p>
          We use essential cookies for authentication and session management via Supabase.
          We do not use tracking cookies or third-party advertising cookies.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">10. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. We will notify users of material
          changes by updating the "Last updated" date. Continued use of the Service after
          changes constitutes acceptance of the revised policy.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-white">11. Contact</h2>
        <p>
          If you have questions about this Privacy Policy or your data, please contact us
          through the Service's support channels.
        </p>
      </section>
    </article>
  )
}
